version: 0.2

phases:
  install:
    commands:
      - pip install flake8 pytest

  pre_build:
    commands:
      - echo "Running lint..."
      - flake8 app.py
      - echo "Running unit tests..."
      - pytest test_app.py -v
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin $ECR_URI

  build:
    commands:
      - IMAGE_TAG=$CODEBUILD_RESOLVED_SOURCE_VERSION
      - docker build -t $ECR_URI:$IMAGE_TAG .
      - docker push $ECR_URI:$IMAGE_TAG
      - docker tag $ECR_URI:$IMAGE_TAG $ECR_URI:latest
      - docker push $ECR_URI:latest

  post_build:
    commands:
      - echo "Build complete. Image tag $IMAGE_TAG pushed to ECR."
